### PR TITLE
set rts and dtr high to avoid MCU hang in bootloader

### PR DESCRIPTION
**Pull request by Josverl**
untested as I was unable to build or test with the instructions.
I hope it builds better on your machine.

https://gist.github.com/Josverl/30adc1eca9ea4eed7ae9a681b85a8dd2

### CODE REVIEW

**Comment by Josverl** [comment]
@jakobrosenberg ,
gentle nudge, could you have a look at integrating this in Pymakr 2 ?

**Comment by jakobrosenberg** [comment]
Hi @Josverl . Sorry completely missed this PR.

**Comment by jakobrosenberg** [comment]
Available in `micropython-ctl-cont@1.13.10`

**Comment by jakobrosenberg** [comment]
And thanks for the PR 😅

**Pull request merged**
